image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node:18-build

stages:
  - test
  - sonar
  - dist
  - artifact
  - review
  - deploy
  - chromatic-publish
  - release
  - bot-publish

audit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - gitlabci-npm-audit break-build --PACKAGE_MANAGER pnpm
    - gitlabci-npm-audit-compare

dist:
  stage: dist
  rules:
    - when: always
  extends:
    - .install
  script:
    # bump version with feature branch name
    - export version=`cat package.json | jq -r '.version'`
    - if [ -z $CI_COMMIT_TAG ]; then version=$version-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID && pnpm version --no-git-tag-version $version; fi;
    - pnpm turbo build
  artifacts:
    expire_in: 1 week
    paths:
      - package.json
      - dist
      - loader
      - www

release:
  rules:
    # only tags
    - if: $CI_COMMIT_TAG
  stage: release
  image: $DOCKER_REGISTRE_URL/$DOCKER_REGISTRE_NAMESPACE_INT/node:16-build
  cache: {}
  script:
    - RELEASE_VERSION=`echo $CI_COMMIT_TAG | cut -c 2-`
    - PACKAGE_VERSION=`cat package.json | jq -r '.version'`
    - if [ $PACKAGE_VERSION != $RELEASE_VERSION ]; then echo Différence de version entre le tag git et le package.json; exit 1; fi;
    - pnpm i
    # we use pnpm, because npm keeps changing its auth behaviour version after version, and it breaks our builds
    - corepack enable
    - pnpm publish --no-git-checks
