version: '3'

services:
  e2e-playwright-test:
    image: 'coreui-e2e:latest'
    ports:
      - 9323:9323
    volumes:
      - ./packages/mg-components:/app/packages/mg-components
      - ./packages/notification-center:/app/packages/notification-center
