version: '3'

services:
  e2e-playwright-test:
    image: 'coreui-e2e:latest'
    ports:
      - 3333:3333
    volumes:
      - ./packages/mg-components/src:/app/packages/mg-components/src
      - ./packages/mg-components/playwright-report:/app/packages/mg-components/playwright-report
      - ./packages/mg-components/test-results:/app/packages/mg-components/test-results
      - ./packages/notification-center/src:/app/packages/notification-center/src
      - ./packages/notification-center/playwright-report:/app/packages/notification-center/playwright-report
      - ./packages/notification-center/test-results:/app/packages/notification-center/test-results
      - ./packages/styles/test:/app/packages/styles/test
      - ./packages/styles/playwright-report:/app/packages/styles/playwright-report
      - ./packages/styles/test-results:/app/packages/styles/test-results
    # Following is based on Playwright recommendation: https://playwright.dev/docs/ci#docker
    init: true
    cap_add:
      - SYS_ADMIN
    ipc: host
