packages:
  # all configs in subdirs of configs/
  - "configs/**"
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all apps in subdirs of apps/
  - "apps/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
