packages:
  # all configs in direct subdirs of configs/
  - 'configs/*'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all apps in direct subdirs of apps/
  - 'apps/*'
  # all tools in direct subdirs of tools/
  - 'tools/*'
  # exclude packages that are inside tests directories
  - '!**/tests/**'
save-prefix: ''
