name: GitHub Pages Storybook Publish

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4

      - run: pnpm i
      - run: pnpm build --filter=@mgdis/mg-components
      - run: pnpm -C packages/mg-components storybook:build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./packages/mg-components/storybook-static
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
